version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: nutrivet_db_dev
    environment:
      POSTGRES_DB: nutrivet_dev
      POSTGRES_USER: nutrivet
      POSTGRES_PASSWORD: nutrivet_dev_pass
    ports:
      - "5432:5432"
    volumes:
      - nutrivet_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nutrivet -d nutrivet_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  nutrivet_pg_data:
