"""add_pets_weight_records_claim_codes

Revision ID: 8703c20c3fc7
Revises: 98f1a4f285a2
Create Date: 2026-03-18 21:03:51.606272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8703c20c3fc7'
down_revision: Union[str, Sequence[str], None] = '98f1a4f285a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('species', sa.Enum('perro', 'gato', name='species_enum'), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.Enum('macho', 'hembra', name='sex_enum'), nullable=False),
    sa.Column('age_months', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('reproductive_status', sa.String(length=30), nullable=False),
    sa.Column('activity_level', sa.String(length=30), nullable=False),
    sa.Column('bcs', sa.Integer(), nullable=False),
    sa.Column('medical_conditions_enc', postgresql.BYTEA(), nullable=True),
    sa.Column('allergies_enc', postgresql.BYTEA(), nullable=True),
    sa.Column('current_diet', sa.String(length=20), nullable=False),
    sa.Column('is_clinic_pet', sa.Boolean(), nullable=False),
    sa.Column('owner_name_hint', sa.String(length=100), nullable=True),
    sa.Column('owner_phone_hint', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pets_owner_id'), 'pets', ['owner_id'], unique=False)
    op.create_table('claim_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_codes_code'), 'claim_codes', ['code'], unique=True)
    op.create_index(op.f('ix_claim_codes_pet_id'), 'claim_codes', ['pet_id'], unique=False)
    op.create_table('weight_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('bcs', sa.Integer(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_records_pet_id'), 'weight_records', ['pet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weight_records_pet_id'), table_name='weight_records')
    op.drop_table('weight_records')
    op.drop_index(op.f('ix_claim_codes_pet_id'), table_name='claim_codes')
    op.drop_index(op.f('ix_claim_codes_code'), table_name='claim_codes')
    op.drop_table('claim_codes')
    op.drop_index(op.f('ix_pets_owner_id'), table_name='pets')
    op.drop_table('pets')
    # ### end Alembic commands ###
