"""add_plans_jobs_substitutes_traces

Revision ID: a808d61e3f56
Revises: 8703c20c3fc7
Create Date: 2026-03-18 21:41:59.614088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a808d61e3f56'
down_revision: Union[str, Sequence[str], None] = '8703c20c3fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_summary', sa.JSON(), nullable=False),
    sa.Column('output_summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_traces_pet_id'), 'agent_traces', ['pet_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_plan_id'), 'agent_traces', ['plan_id'], unique=False)
    op.create_table('plan_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('modality', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'READY', 'FAILED', name='job_status_enum'), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_jobs_owner_id'), 'plan_jobs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_plan_jobs_pet_id'), 'plan_jobs', ['pet_id'], unique=False)
    op.create_table('nutrition_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('plan_type', sa.Enum('estándar', 'temporal_medical', 'life_stage', name='plan_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING_VET', 'ACTIVE', 'UNDER_REVIEW', 'ARCHIVED', name='plan_status_enum'), nullable=False),
    sa.Column('modality', sa.Enum('natural', 'concentrado', name='plan_modality_enum'), nullable=False),
    sa.Column('rer_kcal', sa.Float(), nullable=False),
    sa.Column('der_kcal', sa.Float(), nullable=False),
    sa.Column('weight_phase', sa.String(length=20), nullable=False),
    sa.Column('llm_model_used', sa.String(length=100), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('approved_by_vet_id', sa.UUID(), nullable=True),
    sa.Column('approval_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('vet_comment', sa.Text(), nullable=True),
    sa.Column('agent_trace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_plans_owner_id'), 'nutrition_plans', ['owner_id'], unique=False)
    op.create_index(op.f('ix_nutrition_plans_pet_id'), 'nutrition_plans', ['pet_id'], unique=False)
    op.create_index(op.f('ix_nutrition_plans_status'), 'nutrition_plans', ['status'], unique=False)
    op.create_table('substitute_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('ingredient', sa.String(length=100), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['nutrition_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_substitute_sets_plan_id'), 'substitute_sets', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_substitute_sets_plan_id'), table_name='substitute_sets')
    op.drop_table('substitute_sets')
    op.drop_index(op.f('ix_nutrition_plans_status'), table_name='nutrition_plans')
    op.drop_index(op.f('ix_nutrition_plans_pet_id'), table_name='nutrition_plans')
    op.drop_index(op.f('ix_nutrition_plans_owner_id'), table_name='nutrition_plans')
    op.drop_table('nutrition_plans')
    op.drop_index(op.f('ix_plan_jobs_pet_id'), table_name='plan_jobs')
    op.drop_index(op.f('ix_plan_jobs_owner_id'), table_name='plan_jobs')
    op.drop_table('plan_jobs')
    op.drop_index(op.f('ix_agent_traces_plan_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_pet_id'), table_name='agent_traces')
    op.drop_table('agent_traces')
    # ### end Alembic commands ###
