"""add_label_scans

Revision ID: f5951fc0f352
Revises: a808d61e3f56
Create Date: 2026-03-18 22:14:41.467609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5951fc0f352'
down_revision: Union[str, Sequence[str], None] = 'a808d61e3f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('image_type', sa.String(length=30), nullable=False),
    sa.Column('semaphore', sa.String(length=10), nullable=False),
    sa.Column('ingredients_detected', sa.JSON(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('recomendacion', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_scans_pet_id'), 'label_scans', ['pet_id'], unique=False)
    op.create_index(op.f('ix_label_scans_user_id'), 'label_scans', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_label_scans_user_id'), table_name='label_scans')
    op.drop_index(op.f('ix_label_scans_pet_id'), table_name='label_scans')
    op.drop_table('label_scans')
    # ### end Alembic commands ###
